# Generated by Django 2.1.1 on 2018-09-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('history', models.CharField(max_length=1000)),
                ('cmd_run', models.CharField(max_length=200)),
                ('cmd_kill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('act1', models.FloatField()),
                ('act2', models.FloatField()),
            ],
        ),
    ]
